---
# https://github.com/nornir-automation/nornir-tools/blob/master/tests/virtual/inventory/hosts.yaml
csr1kv:
  hostname: 127.0.0.1
  port: 12204
  data:
    rosetta_parsed_config: ""
    native_config: ""
  groups:
    - ios


eos_device:
  hostname: 127.0.0.1
  port: 8443
  data:
    rosetta_parsed_config: ""
    native_config: ""
  groups:
    - eos
# napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)
# use vagrant port eos for eapi (443 mapping)

junos_device:
  hostname: 127.0.0.1
  port: 12203
  data:
    rosetta_parsed_config: ""
    native_config: ""
  groups:
    - junos
# jnpr.junos.exception.ConnectAuthError: ConnectAuthError(127.0.0.1)
#     raise AuthenticationError(repr(saved_exception))
# ncclient.transport.errors.AuthenticationError: AuthenticationException('Authentication failed.')