openconfig-interfaces:interfaces:
  interface:
  - config:
      enabled: true
      name: GigabitEthernet1
      type: iana-if-type:ethernetCsmacd
    name: GigabitEthernet1
  - config:
      enabled: false
      name: GigabitEthernet2
      type: iana-if-type:ethernetCsmacd
    name: GigabitEthernet2
  - config:
      enabled: false
      name: GigabitEthernet3
      type: iana-if-type:ethernetCsmacd
    name: GigabitEthernet3
openconfig-network-instance:network-instances:
  network-instance:
  - config:
      name: default
    name: default
